# NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list) #a list can be converted to a 1-d array.

array([1, 2, 3])

In [4]:
my_list=[[1,2],[3,4],[5,6]]

In [5]:
np.array(my_list) #a list of lists creates an 2-d array.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0,11) #the simplest way to create an array.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0,11,2) #third argument is the step size.

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3) #prints a 1-d array of 3 zeroes

array([0., 0., 0.])

In [9]:
np.zeros((4,3)) #there is a tuple inside the parameter, which is specifying the dimensions of the 2-d array of zeroes.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,5)) #similarly we can make a matrix of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,6,30) #first number is the start, second input is the stop and third input is the number of divisions 
#you want between them, its a 1d array only.

array([0.        , 0.20689655, 0.4137931 , 0.62068966, 0.82758621,
       1.03448276, 1.24137931, 1.44827586, 1.65517241, 1.86206897,
       2.06896552, 2.27586207, 2.48275862, 2.68965517, 2.89655172,
       3.10344828, 3.31034483, 3.51724138, 3.72413793, 3.93103448,
       4.13793103, 4.34482759, 4.55172414, 4.75862069, 4.96551724,
       5.17241379, 5.37931034, 5.5862069 , 5.79310345, 6.        ])

In [12]:
np.eye(4) #creates an identity matrix of the dimensions of the input given

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5) #if you give one argument it creates 1d matrix and so on..It gives a random number between 0 and 1

array([0.1105487 , 0.7105466 , 0.25253989, 0.20375843, 0.43229015])

In [14]:
np.random.rand(3,2) #note that we are passing individual arguments not tuples 

array([[0.72106109, 0.11542749],
       [0.13817767, 0.04896934],
       [0.96298794, 0.90995466]])

In [15]:
np.random.randn(2) #returns two numbers from a standard normal distribution, you can make it a 2d array too like before

array([ 1.68466855, -0.75182863])

In [16]:
np.random.randint(1,17,3) #low,high,number of integers you want.  

array([ 6, 16,  2])

In [17]:
arr = np.arange(0,25)
arr3=arr.reshape(5,5) #reshapes the 1 d array into a 5 d one.

In [18]:
arr2 = np.random.randint(1,100,6)
print(arr2)
print(arr2.max())
print(arr2.min())
print(arr2.argmax()) #argmax returns the index value of the max element
print(arr2.shape)
print(arr.shape)
print(arr3.shape)

[83 92 69  4 30 72]
92
4
1
(6,)
(25,)
(5, 5)


# NumPy Array Indexing


1D Arrays

In [19]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
print(arr[6])   #slicing
print(arr[1:4])
print(arr[:4])

6
[1 2 3]
[0 1 2 3]


In [21]:
arr[0:5] = 100  #broadcasting. If you take a slice of the original array and change it, the original array will change too.
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [22]:
arr_copy = arr.copy() #method to copy an array. original array is not affected.
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])


2D Arrays

In [23]:
arr_2d = np.array([np.arange(0,3),np.arange(2,5),np.arange(4,7)])
print(arr_2d)
print(arr_2d[1,1]) #grabbing element by row,column

[[0 1 2]
 [2 3 4]
 [4 5 6]]
3


In [24]:
print(arr_2d[:2,:2]) #printing submatrix from the original by method of slicing. first rows then columns.

[[0 1]
 [2 3]]


In [25]:
arr3 = np.arange(0,11)
print(arr3 > 5) #By just one poerator you can get a Boolean array.
boolean = arr3 > 5 #This can be used for conditional selections.
arr[boolean] #Returns an array of True elements only. (Conditional Selection)

[False False False False False False  True  True  True  True  True]


array([ 6,  7,  8,  9, 10])

In [26]:
arr[arr3>5] #Method 2 for the same.

array([ 6,  7,  8,  9, 10])

# NumPy Operations

In [27]:
op = np.arange(0,11)
print(op)
print(op + op) #You can do all kinds of array-array and array-scalar operations.
print(op + 5)
print(op**2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 5  6  7  8  9 10 11 12 13 14 15]
[  0   1   4   9  16  25  36  49  64  81 100]


In [28]:
#Universal array functions. These are math operations you can use across the entire array.
print(np.sqrt(op))
print(np.exp(op))
print(np.sin(op))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
